### ISSUE TITLE
Decrease Image Size

### ISSUE THREAD

**Issue by devshawn** [devshawn/confluent-tools#1]
It would be nice to decrease the image size for the final Docker image. I'm currently using a multi-stage build within the Dockerfile. It currently sits at 460MB.

The image currently includes the full confluent platform. We don't need the full platform, only the tools, but this was the easiest way to quickly get this project going. We should find a way to decrease the size and remove portions of the platform that we don't need.

**Comment by inductor** [comment]
Changing some codes, I could make it to 451MB, but because the confluent tar file is already over 300MB, I do not think there's much to do with it.

I'll show you what I did there anyway...!

FYI, if you don't install bash in alpine and just use ash, the image becomes 447MB.

```Dockerfile
FROM openjdk:8

ENV CONFLUENT_URL=http://packages.confluent.io/archive/5.1/confluent-community-5.1.0-2.11.tar.gz
ENV CONFLUENT_TMP_DEST=/opt/confluent.tgz
ENV CONFLUENT_WORKDIR=/opt/confluent

RUN wget $CONFLUENT_URL -O ${CONFLUENT_TMP_DEST} && \
    mkdir -p ${CONFLUENT_WORKDIR} && \
    tar -xvzpf ${CONFLUENT_TMP_DEST} --strip-components=1 -C ${CONFLUENT_WORKDIR} && \
    rm -rf /opt/confluent/share/doc /opt/confluent/src /opt/confluent/lib

FROM openjdk:8-jre-alpine
RUN apk add --no-cache bash

COPY --from=0 /opt/confluent /opt/confluent
COPY run /opt/confluent/bin/run
ENV PATH /opt/confluent/bin:$PATH

WORKDIR [ "/opt/confluent/bin" ]
ENTRYPOINT [ "tail", "-f", "/dev/null" ]
```

**Comment by inductor** [comment]
@devshawn

**Comment by devshawn** [comment]
@inductor - sorry, I totally missed this... been quite busy. Thanks for looking into this! I'll likely just leave it as is since we don't save much space anyway.
